service: serverless-lambda-easymoney-api

stage: dev

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: /api/user
          method: post
  createdata:
    handler: handler.createdata
    events:
      - http:
          path: /api/data/createdata
          method: post
  getdata:
    handler: handler.getdata
    events:
      - http:
          path: /api/data/{id}
          method: get
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: /api/user/{id}
          method: get
  getAll:
    handler: handler.getAll
    events:
     - http:
         path: /api/user
         method: get
  update:
    handler: handler.update
    events:
     - http:
         path: /api/user/{id}
         method: put
  delete:
    handler: handler.delete
    events:
     - http:
         path: /api/user/{id}
         method: delete

